[project]
name = "akidocs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fpdf2>=2.8.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
